namespace: "mateothegreat"
name: "aws_vpc_create"
version: "0.0.1"
readme: "README.md"
authors:
  - "Matthew Davis (https://matthewdavis.io)"
description: "Provision a complete AWS VPC."
license: ["MIT"]
license_file: "COPYING"
tags: ["cloud", "aws", "vpc"]
repository: "https://github.com/mateothegreat/aws-vpc.git"
homepage: "https://github.com/mateothegreat/aws-vpc"
issues: "https://github.com/mateothegreat/aws-vpc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
